name: Django CI

on:
  workflow_dispatch:
    inputs:
      msg:
        description: 'Message to show'
        default: 'This workflow run is triggered by workflow_dispatch event'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.6]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    # - uses: mr-smithers-excellent/docker-build-push@v6
    #   name: Build & push Docker image
    #   with:
    #     image: 2142420664/test
    #     tags: v1, latest
    #     registry: docker.io
    #     # dockerfile: Dockerfile.ci
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}


    # - name: Build and push doker image
    #   uses: mr-smithers-excellent/docker-build-push@v4 
    #   with:
    
    #     image: 2142420664/test
    #     registry: docker.io
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
